on:
  workflow_dispatch:
    inputs:
      kernel_version:
        required: false
      # Set build_linux, etc to default to true for the cron job.
      # That can be removed when we are comfortable with watcher, and make default false.
      build_linux:
        required: false
        default: 'true'
      build_linux_lts:
        required: false
        default: 'true'
      build_linux_hardened:
        required: false
        default: 'true'
      build_linux_zen:
        required: false
        default: 'true'


  push:
    branches: [master]
    paths:
      - '**.sh'
      - '.github/workflows/**'
      - '!.github/workflows/watcher.yml'
      - 'build-container/**'
      - 'packages/**'
  schedule:
    - cron: "4 2 * * *"

name: Release
run-name: ${{ inputs.kernel_version || 'Manual/Cron' }} release

concurrency:
  group: release
  cancel-in-progress: true

permissions:
  contents: write

env:
  RELEASE_NAME: experimental
  TEMP_RELEASE_NAME: _experimental
  FAILOVER_RELEASE_NAME: failover

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Release

    steps:

      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Build builder container
        env:
          MIRROR_URL: ${{ vars.MIRROR_URL }}
        run: |
          docker build \
          --build-arg MIRROR_URL=${{ env.MIRROR_URL }} \
          -t archzfs-builder build-container

      - name: Run builder container
        env:
          GPG_KEY_DATA: "${{ secrets.GPG_KEY_DATA }}"
          GPG_KEY_ID: "${{ vars.GPG_KEY_ID }}"
          BUILD_LINUX: "${{ inputs.build_linux }}"
          BUILD_LINUX_LTS: "${{ inputs.build_linux_lts }}"
          BUILD_LINUX_HARDENED: "${{ inputs.build_linux_hardened }}"
          BUILD_LINUX_ZEN: "${{ inputs.build_linux_zen }}"
        run: |
          docker run \
          -e GPG_KEY_DATA -e GPG_KEY_ID \
          -e FAILOVER_RELEASE_NAME \
          -e BUILD_LINUX -e BUILD_LINUX_LTS -e BUILD_LINUX_HARDENED -e BUILD_LINUX_ZEN \
          --privileged --rm -v "$(pwd):/src" archzfs-builder

      - name: Delete possible leftover temporary release
        env:
          GH_REPO: "${{ github.repository }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: gh release delete --yes "${{ env.TEMP_RELEASE_NAME }}" || true

      - name: Publish mainline to a temporary release
        uses: ncipollo/release-action@v1.20.0
        with:
          name: ${{ env.TEMP_RELEASE_NAME }}
          tag: ${{ env.TEMP_RELEASE_NAME }}
          commit: ${{ github.sha }}
          artifacts: ./repo/*
          artifactErrorsFailBuild: true
          bodyFile: ci/releases/body-${{ env.RELEASE_NAME }}.md

      - name: Delete the existing mainline release
        env:
          GH_REPO: "${{ github.repository }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: gh release delete --yes "${{ env.RELEASE_NAME }}" || true

      - name: Rename the temporary release to mainline
        env:
          GH_REPO: "${{ github.repository }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: gh release edit --latest --tag "${{ env.RELEASE_NAME }}" --title "${{ env.RELEASE_NAME }}" "${{ env.TEMP_RELEASE_NAME}}"

      - name: Delete the temporary Git tag
        env:
          GH_REPO: "${{ github.repository }}"
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: gh api -X DELETE "repos/${{ github.repository }}/git/refs/tags/${{ env.TEMP_RELEASE_NAME }}"

      - name: Tag the mainline release
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ env.RELEASE_NAME }}
          force_push_tag: true

      - name: Release failover
        uses: ncipollo/release-action@v1.20.0
        with:
          name: ${{ env.FAILOVER_RELEASE_NAME }}
          tag: ${{ env.FAILOVER_RELEASE_NAME }}
          commit: ${{ github.sha }}
          artifacts: ./repo/*
          allowUpdates: true
          artifactErrorsFailBuild: true
          omitBody: true
          omitBodyDuringUpdate: true
          removeArtifacts: true
          prerelease: true

      - name: Tag the failover release
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ env.FAILOVER_RELEASE_NAME }}
          force_push_tag: true
