on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.sh'
      - '.github/workflows/**'
      - 'build-container/**'
      - 'packages/**'

name: Test

concurrency:
  group: test
  cancel-in-progress: true

permissions:
  contents: write

env:
  RELEASE_NAME: testing
  FAILOVER_RELEASE_NAME: failover

jobs:
  test:
    name: Test release
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Build builder container
        run: docker build -t archzfs-builder build-container

      - name: Run builder container
        run: docker run -e FAILOVER_RELEASE_NAME --privileged --rm -v "$(pwd):/src" archzfs-builder

      - name: Release testing
        uses: ncipollo/release-action@v1.20.0
        with:
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_NAME }}
          commit: ${{ github.sha }}
          artifacts: ./repo/*
          allowUpdates: true
          artifactErrorsFailBuild: true
          omitBody: true
          omitBodyDuringUpdate: true
          removeArtifacts: true
          prerelease: true

      - name: Tag the testing release
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ env.RELEASE_NAME }}
          force_push_tag: true
